name: Latex

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: CV.tex
      - uses: actions/upload-artifact@v3
        with:
          name: CV.pdf
          path: CV.pdf
          if-no-files-found: error
  upload:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: CV.pdf
      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: CV.pdf
